name: Optimized CI/CD with Cache

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-optimized:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Cache Next.js build
      uses: actions/cache@v4
      with:
        path: |
          frontend/.next/cache
          frontend/node_modules/.cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-
          
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run linting
      working-directory: ./frontend
      run: npm run lint
      
    - name: Build with cache
      working-directory: ./frontend
      run: npm run build
      
    - name: Check build output
      working-directory: ./frontend
      run: |
        echo "🔍 Checking build output..."
        if [ -d ".next" ]; then
          echo "✅ .next directory exists"
          ls -la .next/
        else
          echo "❌ .next directory not found"
          exit 1
        fi
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-${{ github.sha }}
        path: frontend/.next/
        retention-days: 30
        if-no-files-found: warn

  backend-optimized:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
        
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Security audit
      working-directory: ./backend
      run: |
        # Cross-platform audit check
        npm audit --audit-level=moderate || echo "Audit completed with warnings"
      
    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-files-${{ github.sha }}
        path: backend/
        retention-days: 30

  test-matrix:
    needs: [frontend-optimized, backend-optimized]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 20]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Test frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run lint
        npx tsc --noEmit
        
    - name: Test backend
      working-directory: ./backend
      run: |
        npm ci
        # Windows PowerShell uyumlu audit check
        npm audit --audit-level=moderate || echo "Audit completed with warnings"


