name: Optimized CI/CD with Cache

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-optimized:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Cache Next.js build
      uses: actions/cache@v4
      with:
        path: |
          frontend/.next/cache
          frontend/node_modules/.cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-
          
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run linting
      working-directory: ./frontend
      run: npm run lint
      
    - name: Build with cache
      working-directory: ./frontend
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build-${{ github.sha }}
        path: frontend/.next/
        retention-days: 30

  backend-optimized:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'
        
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Security audit
      working-directory: ./backend
      run: |
        AUDIT_OUTPUT=$(npm audit --audit-level=moderate 2>&1)
        if echo "$AUDIT_OUTPUT" | grep -q "found [1-9]"; then
          echo "Moderate or higher severity vulnerabilities found!"
          echo "$AUDIT_OUTPUT"
          exit 1
        else
          echo "✅ No moderate or higher severity vulnerabilities found"
        fi
      
    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-files-${{ github.sha }}
        path: backend/
        retention-days: 30

  test-matrix:
    needs: [frontend-optimized, backend-optimized]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16, 18, 20]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Test frontend
      working-directory: ./frontend
      run: |
        npm ci
        npm run lint
        npx tsc --noEmit
        
    - name: Test backend
      working-directory: ./backend
      run: |
        npm ci
        AUDIT_OUTPUT=$(npm audit --audit-level=moderate 2>&1)
        if echo "$AUDIT_OUTPUT" | grep -q "found [1-9]"; then
          echo "Moderate or higher severity vulnerabilities found!"
          echo "$AUDIT_OUTPUT"
          exit 1
        else
          echo "✅ No moderate or higher severity vulnerabilities found"
        fi

  deploy-production:
    needs: [frontend-optimized, backend-optimized, test-matrix]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: frontend-build-${{ github.sha }}
        path: ./frontend-build
        
    - name: Deploy to production
      run: |
        echo "🚀 Production'a deploy ediliyor..."
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh
      env:
        DEPLOY_ENV: production
        DEPLOY_HOST: ${{ secrets.PROD_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        BACKEND_URL: ${{ secrets.BACKEND_URL }}
